run_logged $MISTLETOE_INSTALL/config/config.sh
run_logged $MISTLETOE_INSTALL/config/theme.sh
run_logged $MISTLETOE_INSTALL/config/branding.sh
run_logged $MISTLETOE_INSTALL/config/git.sh
run_logged $MISTLETOE_INSTALL/config/gpg.sh
run_logged $MISTLETOE_INSTALL/config/increase-sudo-tries.sh
run_logged $MISTLETOE_INSTALL/config/increase-lockout-limit.sh
run_logged $MISTLETOE_INSTALL/config/ssh-flakiness.sh
run_logged $MISTLETOE_INSTALL/config/detect-keyboard-layout.sh
run_logged $MISTLETOE_INSTALL/config/xcompose.sh
run_logged $MISTLETOE_INSTALL/config/mimetypes.sh
run_logged $MISTLETOE_INSTALL/config/localdb.sh
run_logged $MISTLETOE_INSTALL/config/walker-elephant.sh
run_logged $MISTLETOE_INSTALL/config/fast-shutdown.sh
run_logged $MISTLETOE_INSTALL/config/input-group.sh
run_logged $MISTLETOE_INSTALL/config/hardware/network.sh
run_logged $MISTLETOE_INSTALL/config/hardware/set-wireless-regdom.sh
run_logged $MISTLETOE_INSTALL/config/hardware/bluetooth.sh
run_logged $MISTLETOE_INSTALL/config/hardware/usb-autosuspend.sh
run_logged $MISTLETOE_INSTALL/config/hardware/ignore-power-button.sh
run_logged $MISTLETOE_INSTALL/config/hardware/fix-f13-amd-audio-input.sh