# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

source = ~/.config/hypr/hyprland/autostart.conf
source = ~/.config/hypr/hyprland/monitors.conf
source = ~/.config/hypr/hyprland/input.conf
source = ~/.config/hypr/hyprland/keybindings.conf
source = ~/.config/hypr/hyprland/envs.conf
source = ~/.config/hypr/hyprland/general.conf
source = ~/.config/hypr/hyprland/windowrules.conf
source = ~/.config/mistletoe/current/theme/hyprland.conf